### ISSUE TITLE
replace twitter link

### ISSUE THREAD

**Issue by krrisis** [commons-stack/website#15]
plz link the logo for twitter no longer to giveth but to twitter.com/commons_stack

**Comment by MaxSemenchuk** [comment]
Resolved, also do you want me to teach you how to work with Tilda?

**Comment by krrisis** [comment]
Good point, that is one I could've done myself, still have the login details :)
